export const BOOKING_STATUS = Object.freeze({
  CREATED: "CREATED",
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  CONFIRMED: "CONFIRMED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED_BY_TOURIST: "CANCELLED_BY_TOURIST",
  CANCELLED_BY_GUIDE: "CANCELLED_BY_GUIDE",
  DISPUTED: "DISPUTED"
});

export const PAYMENT_ENTRY_STATUSES = new Set([
  BOOKING_STATUS.CREATED,
  BOOKING_STATUS.PENDING_PAYMENT,
  BOOKING_STATUS.PAYMENT_FAILED
]);

export const PAYMENT_INTENT_CREATION_STATUSES = new Set([
  BOOKING_STATUS.CREATED,
  BOOKING_STATUS.PAYMENT_FAILED
]);

export const CANCELLABLE_BOOKING_STATUSES = new Set([
  BOOKING_STATUS.CREATED,
  BOOKING_STATUS.PENDING_PAYMENT,
  BOOKING_STATUS.CONFIRMED,
  BOOKING_STATUS.PAYMENT_FAILED
]);
